### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by gladson** [Surendra-Patil/Django-Nginx#4]
![1](https://i.imgur.com/zEEdn3k.png)
![2](https://i.imgur.com/8yM4JuN.png)
![3](https://i.imgur.com/wivOSrt.png)

**Comment by Surendra-Patil** [comment]
I will shortly fix the issue and get back to you.

**Comment by Surendra-Patil** [comment]
@gladson 

I have resolved the error. Kindly check. 

![image](https://user-images.githubusercontent.com/8789772/93189262-8eebe700-f75f-11ea-8817-08d06fdede4d.png)


I have forced https enabled with a domain "example.com" which you might want to change with your domain for that you would have to rename in all three files (Dockerfile, nginx.conf, ssl.sh) on https://github.com/Surendra-Patil/Django-Nginx/tree/master/nginx

**Comment by gladson** [comment]
Hello @Surendra-Patil , how are you...

Thank you for answering.

👍🏾 

But it continues with the problem of:

```shell
> Executing task: docker logs -f 41efcb9f2fc91830106b5f3e35235fed97303307588553aa9f4711d832bdd0a2 <

Waiting for postgres...
PostgreSQL started
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
Deleting 'admin/css/autocomplete.css'
Deleting 'admin/css/base.css'
Deleting 'admin/css/changelists.css'
Deleting 'admin/css/dashboard.css'
Deleting 'admin/css/fonts.css'
Deleting 'admin/css/forms.css'
Deleting 'admin/css/login.css'
Deleting 'admin/css/nav_sidebar.css'
Deleting 'admin/css/responsive.css'
Deleting 'admin/css/responsive_rtl.css'
Deleting 'admin/css/rtl.css'
Deleting 'admin/css/widgets.css'
Deleting 'admin/css/vendor/select2/LICENSE-SELECT2.md'
Deleting 'admin/css/vendor/select2/select2.css'
Deleting 'admin/css/vendor/select2/select2.min.css'
Deleting 'admin/fonts/LICENSE.txt'
Deleting 'admin/fonts/README.txt'
Deleting 'admin/fonts/Roboto-Bold-webfont.woff'
Deleting 'admin/fonts/Roboto-Light-webfont.woff'
Deleting 'admin/fonts/Roboto-Regular-webfont.woff'
Deleting 'admin/img/calendar-icons.svg'
Deleting 'admin/img/icon-addlink.svg'
Deleting 'admin/img/icon-alert.svg'
Deleting 'admin/img/icon-calendar.svg'
Deleting 'admin/img/icon-changelink.svg'
Deleting 'admin/img/icon-clock.svg'
Deleting 'admin/img/icon-deletelink.svg'
Deleting 'admin/img/icon-no.svg'
Deleting 'admin/img/icon-unknown-alt.svg'
Deleting 'admin/img/icon-unknown.svg'
Deleting 'admin/img/icon-viewlink.svg'
Deleting 'admin/img/icon-yes.svg'
Deleting 'admin/img/inline-delete.svg'
Deleting 'admin/img/LICENSE'
Deleting 'admin/img/README.txt'
Deleting 'admin/img/search.svg'
Deleting 'admin/img/selector-icons.svg'
Deleting 'admin/img/sorting-icons.svg'
Deleting 'admin/img/tooltag-add.svg'
Deleting 'admin/img/tooltag-arrowright.svg'
Deleting 'admin/img/gis/move_vertex_off.svg'
Deleting 'admin/img/gis/move_vertex_on.svg'
Deleting 'admin/js/actions.js'
Deleting 'admin/js/actions.min.js'
Deleting 'admin/js/autocomplete.js'
Deleting 'admin/js/calendar.js'
Deleting 'admin/js/cancel.js'
Deleting 'admin/js/change_form.js'
Deleting 'admin/js/collapse.js'
Deleting 'admin/js/collapse.min.js'
Deleting 'admin/js/core.js'
Deleting 'admin/js/inlines.js'
Deleting 'admin/js/inlines.min.js'
Deleting 'admin/js/jquery.init.js'
Deleting 'admin/js/nav_sidebar.js'
Deleting 'admin/js/popup_response.js'
Deleting 'admin/js/prepopulate.js'
Deleting 'admin/js/prepopulate.min.js'
Deleting 'admin/js/prepopulate_init.js'
Deleting 'admin/js/SelectBox.js'
Deleting 'admin/js/SelectFilter2.js'
Deleting 'admin/js/urlify.js'
Deleting 'admin/js/admin/DateTimeShortcuts.js'
Deleting 'admin/js/admin/RelatedObjectLookups.js'
Deleting 'admin/js/vendor/jquery/jquery.js'
Deleting 'admin/js/vendor/jquery/jquery.min.js'
Deleting 'admin/js/vendor/jquery/LICENSE.txt'
Deleting 'admin/js/vendor/select2/LICENSE.md'
Deleting 'admin/js/vendor/select2/select2.full.js'
Deleting 'admin/js/vendor/select2/select2.full.min.js'
Deleting 'admin/js/vendor/select2/i18n/is.js'
Deleting 'admin/js/vendor/select2/i18n/af.js'
Deleting 'admin/js/vendor/select2/i18n/ar.js'
Deleting 'admin/js/vendor/select2/i18n/az.js'
Deleting 'admin/js/vendor/select2/i18n/bg.js'
Deleting 'admin/js/vendor/select2/i18n/bn.js'
Deleting 'admin/js/vendor/select2/i18n/bs.js'
Deleting 'admin/js/vendor/select2/i18n/ca.js'
Deleting 'admin/js/vendor/select2/i18n/cs.js'
Deleting 'admin/js/vendor/select2/i18n/da.js'
Deleting 'admin/js/vendor/select2/i18n/de.js'
Deleting 'admin/js/vendor/select2/i18n/dsb.js'
Deleting 'admin/js/vendor/select2/i18n/el.js'
Deleting 'admin/js/vendor/select2/i18n/en.js'
Deleting 'admin/js/vendor/select2/i18n/es.js'
Deleting 'admin/js/vendor/select2/i18n/et.js'
Deleting 'admin/js/vendor/select2/i18n/eu.js'
Deleting 'admin/js/vendor/select2/i18n/fa.js'
Deleting 'admin/js/vendor/select2/i18n/fi.js'
Deleting 'admin/js/vendor/select2/i18n/fr.js'
Deleting 'admin/js/vendor/select2/i18n/gl.js'
Deleting 'admin/js/vendor/select2/i18n/he.js'
Deleting 'admin/js/vendor/select2/i18n/hi.js'
Deleting 'admin/js/vendor/select2/i18n/hr.js'
Deleting 'admin/js/vendor/select2/i18n/hsb.js'
Deleting 'admin/js/vendor/select2/i18n/hu.js'
Deleting 'admin/js/vendor/select2/i18n/hy.js'
Deleting 'admin/js/vendor/select2/i18n/id.js'
Deleting 'admin/js/vendor/select2/i18n/it.js'
Deleting 'admin/js/vendor/select2/i18n/ja.js'
Deleting 'admin/js/vendor/select2/i18n/ka.js'
Deleting 'admin/js/vendor/select2/i18n/km.js'
Deleting 'admin/js/vendor/select2/i18n/ko.js'
Deleting 'admin/js/vendor/select2/i18n/lt.js'
Deleting 'admin/js/vendor/select2/i18n/lv.js'
Deleting 'admin/js/vendor/select2/i18n/mk.js'
Deleting 'admin/js/vendor/select2/i18n/ms.js'
Deleting 'admin/js/vendor/select2/i18n/nb.js'
Deleting 'admin/js/vendor/select2/i18n/ne.js'
Deleting 'admin/js/vendor/select2/i18n/nl.js'
Deleting 'admin/js/vendor/select2/i18n/pl.js'
Deleting 'admin/js/vendor/select2/i18n/ps.js'
Deleting 'admin/js/vendor/select2/i18n/pt-BR.js'
Deleting 'admin/js/vendor/select2/i18n/pt.js'
Deleting 'admin/js/vendor/select2/i18n/ro.js'
Deleting 'admin/js/vendor/select2/i18n/ru.js'
Deleting 'admin/js/vendor/select2/i18n/sk.js'
Deleting 'admin/js/vendor/select2/i18n/sl.js'
Deleting 'admin/js/vendor/select2/i18n/sq.js'
Deleting 'admin/js/vendor/select2/i18n/sr-Cyrl.js'
Deleting 'admin/js/vendor/select2/i18n/sr.js'
Deleting 'admin/js/vendor/select2/i18n/sv.js'
Deleting 'admin/js/vendor/select2/i18n/th.js'
Deleting 'admin/js/vendor/select2/i18n/tk.js'
Deleting 'admin/js/vendor/select2/i18n/tr.js'
Deleting 'admin/js/vendor/select2/i18n/uk.js'
Deleting 'admin/js/vendor/select2/i18n/vi.js'
Deleting 'admin/js/vendor/select2/i18n/zh-CN.js'
Deleting 'admin/js/vendor/select2/i18n/zh-TW.js'
Deleting 'admin/js/vendor/xregexp/LICENSE.txt'
Deleting 'admin/js/vendor/xregexp/xregexp.js'
Deleting 'admin/js/vendor/xregexp/xregexp.min.js'
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 355, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 291, in _save
    os.chmod(full_path, self.file_permissions_mode)
PermissionError: [Errno 1] Operation not permitted: '/home/app/web/staticfiles/admin/fonts/Roboto-Light-webfont.woff'
[2020-09-17 03:57:52 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-09-17 03:57:52 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-09-17 03:57:52 +0000] [1] [INFO] Using worker: sync
[2020-09-17 03:57:52 +0000] [32] [INFO] Booting worker with pid: 32
```
![image](https://user-images.githubusercontent.com/1013698/93418875-53ddd680-f879-11ea-8f56-5764d57affb2.png)
![image](https://user-images.githubusercontent.com/1013698/93418903-69eb9700-f879-11ea-8421-30c026b9be5f.png)
